#  menu items
[[main]]
  name = "Blog"
  weight = 5
  url = "blog/"

# [[main]]
#   name = "Blog IOT"
#   weight = 4
#   url = "blogiot/"

# [[main]]
#   name = "Docs"
#   weight = 2
#   url = "docs/"

[[main]]
  name = "Old Blogs"
  weight = 7
  url = "blogarc/"



[[main]]
  name = "Tutorials"
  weight = 12
  url = "tutorials/"

# [[main]]
#   name = "Blog"
#   weight = 4
#   url = "blog/"


